name: bluetooth_p
description: "Bluetooth App Protocol"
publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  #iOS图标
  cupertino_icons: ^1.0.8
  #用于中心设备
  flutter_blue_plus: ^1.35.5
  #用于外围设备 实际版本是^6.1.0，Android侧修改了蓝牙是否可用的判断
  bluetooth_low_energy:
    path: ./bluetooth_low_energy/bluetooth_low_energy
  permission_handler: ^12.0.1
  #设备信息获取: https://pub-web.flutter-io.cn/packages/device_info_plus
  device_info_plus: ^11.5.0
  #获取版本号: https://pub-web.flutter-io.cn/packages/package_info_plus
  package_info_plus: ^8.3.0
  #扩展集合功能的工具包 https://pub-web.flutter-io.cn/packages/collection
  collection: ^1.19.1
  characters: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
